//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrimeCmd.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PrimeCmd.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap connected {
            get {
                object obj = ResourceManager.GetObject("connected", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap disconnected {
            get {
                object obj = ResourceManager.GetObject("disconnected", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All supported files|*.hpprgm;*.txt;*.bmp;*.gif;*.jpeg;*.jpg;*.png|HP Prime Program (*.hpprgm)|*.hpprgm|Text files (*.txt)|*.txt|Images|*.bmp;*.gif;*.jpeg;*.jpg;*.png|All files (*.*)|*.*.
        /// </summary>
        internal static string FilterInput {
            get {
                return ResourceManager.GetString("FilterInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HP Prime Program (*.hpprgm)|*.hpprgm|Text files (*.txt)|*.txt|All files (*.*)|*.*.
        /// </summary>
        internal static string FilterOutput {
            get {
                return ResourceManager.GetString("FilterOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string MsgErrorTitle {
            get {
                return ResourceManager.GetString("MsgErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error sending the file.
        /// </summary>
        internal static string SendError {
            get {
                return ResourceManager.GetString("SendError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not supported file.
        /// </summary>
        internal static string SendNotSupported {
            get {
                return ResourceManager.GetString("SendNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t send files.
        /// </summary>
        internal static string StatusAllFailed {
            get {
                return ResourceManager.GetString("StatusAllFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All the files were sucessfully sent!.
        /// </summary>
        internal static string StatusAllSent {
            get {
                return ResourceManager.GetString("StatusAllSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected to USB.
        /// </summary>
        internal static string StatusConnected {
            get {
                return ResourceManager.GetString("StatusConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not connected.
        /// </summary>
        internal static string StatusNotConnected {
            get {
                return ResourceManager.GetString("StatusNotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receiving ({0} KB received)....
        /// </summary>
        internal static string StatusReceived {
            get {
                return ResourceManager.GetString("StatusReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending files....
        /// </summary>
        internal static string StatusSending {
            get {
                return ResourceManager.GetString("StatusSending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending ({0} of {1})....
        /// </summary>
        internal static string StatusSendingProgress {
            get {
                return ResourceManager.GetString("StatusSendingProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File sucessfully sent!.
        /// </summary>
        internal static string StatusSent {
            get {
                return ResourceManager.GetString("StatusSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some files failed. Check the device.
        /// </summary>
        internal static string StatusSomeFailed {
            get {
                return ResourceManager.GetString("StatusSomeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting, select a program and tap Send in your calculator....
        /// </summary>
        internal static string StatusWaiting {
            get {
                return ResourceManager.GetString("StatusWaiting", resourceCulture);
            }
        }
    }
}
